enabled: true

image:
  name: quay.io/giantswarm/cluster-api-ipam-provider-in-cluster
  # todo: switch back to latest released image once they release
  tag: 80ec908

project:
  branch: ""
  commit: ""

crds:
  install: true
  jobRegistry: quay.io

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

inClusterIpPool:
  enabled: false
  pools:
  - name: wc-cp-ips
    # use either start & end or addresses
    start: 10.10.222.222
    end: 10.10.222.225
    # addresses:
    # - 10.10.222.223/28
  - name: svc-lb-ips
    start: 10.10.222.226
    end: 10.10.222.229

ciliumNetworkPolicy:
  enabled: false

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

global:
  podSecurityStandards:
    enforced: false
