enabled: true

image:
  name: quay.io/giantswarm/cluster-api-ipam-provider-in-cluster
  # todo: switch back to latest released image once they release
  tag: 80ec908

project:
  branch: ""
  commit: ""

crds:
  install: true
  jobRegistry: quay.io

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

inClusterIpPool:
  enabled: false
  name: wc-cp-ips
  # use either start & end or adresses
  start: 10.10.222.222
  end: 10.10.222.229
  # addresses:
  # - 10.10.222.223/28

ciliumNetworkPolicy:
  enabled: false
