namespace: '{{ .Release.Namespace }}'

resources:
- input/ipam-components.yaml

transformers:
- patches/common-labels.yaml
- patches/monitoring-annotations.yaml

patchesStrategicMerge:
- patches/delete-namespace.yaml
- patches/certificate.yaml
- patches/webhook-certificate.yaml
- patches/delete-issuer.yaml
- patches/deployment-resources.yaml

patches:
- path: patches/crd_cainjection.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=ipam-in-cluster
- path: patches/crd_webhook.yaml
  target:
    kind: CustomResourceDefinition
    labelSelector: cluster.x-k8s.io/provider=ipam-in-cluster
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes/0
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
  target:
    group: apps
    kind: Deployment
    name: caip-in-cluster-controller-manager
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
