{{- if .Values.inClusterIpPool.enabled }}
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: {{ .Values.inClusterIpPool.name }}
spec:
  gateway: 0.0.0.0
  prefix: 24
{{- with .Values.inClusterIpPool.start }}
  start: {{ . }}
{{- end }}
{{- with .Values.inClusterIpPool.end }}
  end: {{ . }}
{{- end }}
{{- with .Values.inClusterIpPool.addresses }}
  addresses:
  {{- range . }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
