{{- if .Values.enabled }}
{{- with .Values.inClusterIpPool }}
{{- if .enabled }}
{{- range .pools }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-pool-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
data:
  content: |
    apiVersion: ipam.cluster.x-k8s.io/v1alpha2
    kind: GlobalInClusterIPPool
    metadata:
      name: {{ .name }}
    spec:
      gateway: 0.0.0.0
      prefix: 24
      addresses:
      {{- if .start }}
      - {{ .start }}-{{ .end }}
      {{- end }}
      {{- range .addresses }}
      - {{ . }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
