{{- if .Values.enabled }}
{{- with .Values.inClusterIpPool }}
{{- if .enabled }}
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: {{ .name }}
spec:
  gateway: 0.0.0.0
  prefix: 24
{{- if .start }}
  start: {{ .start }}
  end: {{ .end }}
{{- else }}
  addresses:
  {{- range .addresses }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
