{{- if .Values.enabled }}
{{- if .Values.inClusterIpPool.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: install-crs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-crs
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - inclusterippools
  verbs:
  - patch
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  resourceNames:
  - inclusterippools.ipam.cluster.x-k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: install-crs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: install-crs
subjects:
- kind: ServiceAccount
  name: install-crs
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
