{{- if .Values.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/caip-in-cluster-serving-cert'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
    cluster.x-k8s.io/provider: ipam-in-cluster
    helm.sh/chart: '{{ .Chart.Name }}'
  name: caip-in-cluster-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: caip-in-cluster-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-ipam-cluster-x-k8s-io-v1alpha2-inclusterippool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.inclusterippool.ipam.cluster.x-k8s.io
  rules:
  - apiGroups:
    - ipam.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - inclusterippools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: caip-in-cluster-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-ipam-cluster-x-k8s-io-v1alpha2-globalinclusterippool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.globalinclusterippool.ipam.cluster.x-k8s.io
  rules:
  - apiGroups:
    - ipam.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - globalinclusterippools
  sideEffects: None
{{- end }}
