{{- if .Values.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: ipam-in-cluster
    helm.sh/chart: '{{ .Chart.Name }}'
  name: caip-in-cluster-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - caip-in-cluster-webhook-service.{{ .Release.Namespace }}.svc
  - caip-in-cluster-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: caip-in-cluster-webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle
{{- end }}
