{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: ipam-in-cluster
    control-plane: controller-manager
    helm.sh/chart: '{{ .Chart.Name }}'
  name: caip-in-cluster-controller-manager-metrics-service
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    cluster.x-k8s.io/provider: ipam-in-cluster
    control-plane: controller-manager
{{- end }}
