---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: caip-in-cluster-serving-cert
  namespace: caip-in-cluster-system
spec:
  dnsNames:
    - caip-in-cluster-webhook-service.{{ .Release.Namespace }}.svc
    - caip-in-cluster-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: caip-in-cluster-webhook-service-cert
