# We have our Issuer already deployed to clusters.
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: caip-in-cluster-selfsigned-issuer
  namespace: caip-in-cluster-system
