---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caip-in-cluster-controller-manager
  namespace: caip-in-cluster-system
spec:
  template:
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: manager
          image: "{{.Values.image.name}}:{{.Values.image.tag}}"
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capv-webhook-server-cert
