---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: caip-in-cluster-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/caip-serving-cert"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: caip-in-cluster-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/caip-serving-cert"
